In [24]:
import pandas as pd 
import numpy as np

In [25]:
path = "\\\sysdatprod1\\Cartridge Complaint Data\\GEM5000\\16010210\\000000000500219394\\000000000500219394_20211021_111233\\SENSOR.csv"

In [26]:
data = pd.read_csv(path, low_memory=False, header=None, names=list(range(65)))
search = data.iloc[:,1].to_list()
index = 0
while search[index]!="'CartAge'":
    index+=1
data.columns = data.iloc[index,:]
data = data.iloc[index+1:,:]
data.reset_index()

1,index,'10/21/21 11:12:34.003','CartAge','CalType','Hct','Na','K','Ca','BUN','Cl',...,'waveEnd','mean A','mean SD','meanTellTale','maxTellTale','Ne585peakCPS','Ne585intgCPS','f_biliFactor','BiliMeas','BiliCalc'
0,2,'10/21/21 11:12:34.009','Instrument',NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,'10/21/21 11:12:34.011','Script','WARMUP',47.0000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,'10/21/21 11:12:34.013','FPGA',NaN,7.11,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,'10/21/21 11:12:34.015','GemScript',NaN,0.904,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,'10/21/21 11:12:34.018','LotNo',NaN,210902J,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47747,47749,'11/21/21 11:01:13.886',743.95,'B-MEAS',15.81354,156.11581,1.96614,0.79013,NaN,85.55351,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.00411
47748,47750,'11/21/21 11:01:13.886',743.95,'ERRS',NaN,NaN,NaN,NaN,'UNASSIGNED',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47749,47751,'11/21/21 11:01:13.889',743.95,'B-DRIFT',-0.08646,0.81581,0.00614,0.00213,NaN,-0.54649,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.00411
47750,47752,'11/21/21 11:01:13.889',743.95,'ERRS',NaN,NaN,NaN,NaN,'UNASSIGNED',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47751,47753,'11/21/21 11:04:39.425','Script','REMOVE_CART',10.0000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
data.head()
print(data.columns)

Index([''10/21/21 11:12:34.003'', ''CartAge'', ''CalType'', ''Hct'', ''Na'',
       ''K'', ''Ca'', ''BUN'', ''Cl'', ''pO2'', ''pH'', ''HCO3'', ''Crea'',
       ''Cr'', ''Lac'', ''Glu'', ''Ref'', ''Gnd'', ''pCO2'', ''TECchem'',
       ''PADchem'', ''ChemStep'', ''AspStep'', ''CooxStep'', ''OOtemp'',
       ''PADspec'', ''TECcoox'', ''PADcoox'', ''Int_Time'', ''Peak_Int'',
       ''FB_Current'', ''DK_mean'', ''AVG_DK_Int'', ''f_factor'', ''tHbMeas'',
       ''tHbCalc'', ''%O2Hb'', ''%COHb'', ''%MetHb'', ''%HHb'', ''O2Hb'',
       ''COHb'', ''MetHb'', ''HHb'', ''SHb'', ''Turbid'', ''Turbid2'',
       ''CNmetHb'', ''%Fetal'', ''%Adult'', ''FetalConc'', ''Adult1Conc'',
       ''Adult2Conc'', ''avgRsid'', ''waveStrt'', ''waveEnd'', ''mean A'',
       ''mean SD'', ''meanTellTale'', ''maxTellTale'', ''Ne585peakCPS'',
       ''Ne585intgCPS'', ''f_biliFactor'', ''BiliMeas'', ''BiliCalc''],
      dtype='object', name=1)